-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgp/nDEesmlyR7es89Ufd4DrG/vf+gmh9Sj8NogwzuQ5egCgYIKoZIzj0DAQehRANCAARIwiSFhcJ+iAdqMuMSrbkrbsWz6/I05GO+Vo3bn4M8iW2dLkAo2s/JC2akNydjVHFrapB08yH1MtEgI/rQsg0S
-----END PRIVATE KEY-----