FORMAT: 1A
HOST: http://pluto.treecom.net:8088/

# TolloT API Documentation

API Docs...

- API URL: http://pluto.treecom.net:8088/
- X-Auth-Token header is WC device token

## WC Collection [/wc]

### List WCs [GET /wc{?cateogry}]

List of toilets.

Header is optional.


+ Parameters

    + category: "2oucniwjni" (optional, string) - Filter by category id

+ Request

    + Headers

            X-Auth-Token: JCAiSjGefNprusgyRmtN51_CoQUutKOa9cPBu18kDCI


+ Response 200 (application/json)

    + Body

            {
                "status": "success",
                "data": [
                        {
                            "_id":"2ud92939dj203j0d2j923jd",
                            "categoryId": "982j9f8h2983fh98",
                            "status": true,
                            "active": true,
                            "token": "28f9j394hf87hh4f",
                            "title": "Hore",
                            "inactivity": 0,
                            "usageCount": 123,
                            "banner": "http://someurl.com/banner.jpg"
                        }
                ]
            }

### Get WC state [GET /wc/{_id}]

Get toilate state. Header is optional.

+ Parameters

    + _id: "2oucniwjni" (optional, string) - Toilet id

+ Request

    + Headers

            X-Auth-Token: JCAiSjGefNprusgyRmtN51_CoQUutKOa9cPBu18kDCI


+ Response 200 (application/json)

    + Body

            {
                "status": "success",
                "data": {
                        "_id":"2ud92939dj203j0d2j923jd",
                        "categoryId": "982j9f8h2983fh98",
                        "status": true,
                        "active": true,
                        "token": "28f9j394hf87hh4f",
                        "title": "Hore",
                        "inactivity": 0,
                        "usageCount": 5,
                        "banner": "http://someurl.com/banner.jpg"
                    }

            }

+ Response 404 (application/json)

    + Body

            {
                "status": "error",
                "message": "WC not found"
            }


### Get WC state with token [PUT /wc/token/{token}]

Get toilate state as manager. Header is optional.

+ Parameters

    + token: "28f9j394hf87hh4f" (optional, string) - Toilet token


+ Response 200 (application/json)

    + Body

            {
                "status": "success",
                "data": {
                        "_id":"2ud92939dj203j0d2j923jd",
                        "categoryId": "982j9f8h2983fh98",
                        "status": true,
                        "active": true,
                        "token": "28f9j394hf87hh4f",
                        "title": "Hore",
                        "inactivity": 0,
                        "usageCount": 5,
                        "banner": "http://someurl.com/banner.jpg"
                    }

            }

+ Response 404 (application/json)

    + Body

            {
                "status": "error",
                "message": "WC not found"
            }



### Subscribe to WC [POST /wc/{_id}/subsribe]

Subscribe user mobile to WC. If header with wc token is set it mean manager is subscribing to alerts.

Header is optional.

+ Parameters

    + _id: "2oucniwjni" (optional, string) - Toilet ID


+ Request (application/json)


    + Headers

            X-Auth-Token: JCAiSjGefNprusgyRmtN51_CoQUutKOa9cPBu18kDCI


    + Body

            {
                "deviceToken": "wd8278hd72hduh23du2h3d8i2uh3d2u"
            }

+ Response 200 (application/json)


    + Body

            {
               "status": "success"
            }



### Unsubscribe to WC [POST /wc/{_id}/unsubsribe]


Unsubscribe user mobile from WC. If header with wc token is set it mean manager is subscribing to alerts.

Header is optional.


+ Parameters

    + _id: "2oucniwjni" (optional, string) - Toilet ID


+ Request (application/json)


    + Headers

            X-Auth-Token: JCAiSjGefNprusgyRmtN51_CoQUutKOa9cPBu18kDCI

    + Body


            {
                "deviceToken": "wd8278hd72hduh23du2h3d8i2uh3d2u"
            }

+ Response 200 (application/json)

    + Body

            {
               "status": "success"
            }


### WC states report [GET /wc/{_id}/last{?from}]

Header is required.


+ Parameters

    + from: 2017-02-01 (optional, string) - From date


+ Request (application/json)


    + Headers

            X-Auth-Token: JCAiSjGefNprusgyRmtN51_CoQUutKOa9cPBu18kDCI


+ Response 200 (application/json)

    + Body

            {
                "status": "success"
                "data": [
                    {
                        "_id": "lxmlaksxmlkasml"
                    }
                ]
            }


### Update WC  [PUT /wc/{_id}]

Update WC Setttings.

Header is required.

+ Request (application/json)


    + Headers

            X-Auth-Token: JCAiSjGefNprusgyRmtN51_CoQUutKOa9cPBu18kDCI

    + Body

            {
                "banner": "http://someurl.com/banner.jpg"
            }

+ Response 200 (application/json)

    + Body

            {
               "status": "success",
               "data": {
                    "categoryId": "982j9f8h2983fh98",
                    "status": true,
                    "active": true,
                    "token": "28f9j394hf87hh4f",
                    "title": "Hore",
                    "inactivity": 0,
                    "usageCount": 5,
                    "banner": "http://someurl.com/banner.jpg"
                }
            }




## Categories Collection [/categories]

### Get categories [GET /categories]


+ Response 200 (application/json)


            {
                "status": "success",
                "data": [
                    {
                        "_id": "98hf92h7387f4873gf87g",
                        "title": "Kosice"
                    }
                ]
            }


## Reports Collection [/reports]

### Get reports [GET /reports]

Header is required.

+ Request

    + Headers

            X-Auth-Token: JCAiSjGefNprusgyRmtN51_CoQUutKOa9cPBu18kDCI


+ Response 200 (application/json)


            {
                "status": "success",
                "data": [
                    {
                        "idWc": "ro2i3niof32i2"
                    }
                ]
            }

